<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>CastDesktop</RootNamespace>
    <AssemblyName>CastDesktop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sharpcaster" Version="3.0.0" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ffmpeg.exe" Condition="Exists('ffmpeg.exe')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
